<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Codesearch.Embeddings\Codesearch.Embeddings.csproj" />
    <ProjectReference Include="..\Codesearch.Interop\Codesearch.Interop.csproj" />
  </ItemGroup>
</Project>
