using System.Text;

namespace Miller.Indexing;

/// <summary>
/// The filesystem edge for <see cref="VendorScan"/> — the consumer-side port of julie's
/// <c>generate_julieignore_file()</c>. When a workspace root has NO <c>.julieignore</c>, it enumerates the
/// tree (bounded, skipping VCS/tool internals but deliberately DESCENDING into vendor-named dirs so they can
/// be detected), runs the pure detection, and writes a seeded <c>.julieignore</c> with the baseline noise
/// patterns plus any detected vendor directories. The generated file then flows everywhere ignore policy
/// already flows: julie-extract reads it from the root on full scans (Miller passes no <c>--ignore-file</c>),
/// and the watcher's <c>WorkspaceIgnorePolicy</c> reads the same file for live events.
///
/// <para>Contract: NEVER overwrites or appends to an existing <c>.julieignore</c> (a user-authored file is
/// authoritative; deleting the generated one and rescanning regenerates from scratch). Best-effort: any I/O
/// failure returns false rather than throwing — seeding hygiene must never break the scan that triggered it.
/// The pure pieces (<see cref="RenderContent"/>, <see cref="VendorScan"/>) are fast-suite-testable; only the
/// enumeration/write here touches the real filesystem.</para>
/// </summary>
public static class JulieIgnoreSeeder
{
    /// <summary>Bound on the detection walk so a first scan of a huge tree stays cheap. The name-matched
    /// threshold (&gt;5 files) saturates long before this; the cap only limits cluster detection depth.</summary>
    internal const int MaxEnumeratedFiles = 25_000;

    // Internal dirs the detection walk skips outright: their contents are never indexable and never
    // vendor evidence. NOTE: vendor-named dirs (node_modules, target, ...) are NOT here — the walk must
    // see inside them to detect them (julie's phase-1 "vendor scan" walk does the same).
    private static readonly HashSet<string> WalkSkipDirectories = new(StringComparer.Ordinal)
    {
        ".git",
        ".hg",
        ".svn",
        ".miller",
        ".julie",
        ".vs",
        ".cache",
        ".memories",
    };

    /// <summary>
    /// Seed <c>&lt;workspaceRoot&gt;/.julieignore</c> when none exists. Returns true only when a new file was
    /// written; false when one already exists (never overwritten), the root is missing, or any I/O step
    /// failed (best-effort — never throws).
    /// </summary>
    /// <exception cref="ArgumentException"><paramref name="workspaceRoot"/> is null or blank.</exception>
    public static bool EnsureSeeded(string workspaceRoot)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(workspaceRoot);
        try
        {
            string ignorePath = Path.Combine(workspaceRoot, ".julieignore");
            if (File.Exists(ignorePath) || !Directory.Exists(workspaceRoot))
                return false;

            IReadOnlyList<string> vendorDirectories =
                VendorScan.DetectVendorDirectories(EnumerateRelativeFiles(workspaceRoot));
            File.WriteAllText(ignorePath, RenderContent(vendorDirectories, DateTime.UtcNow));
            return true;
        }
        catch (Exception ex) when (
            ex is IOException or UnauthorizedAccessException or System.Security.SecurityException
               or NotSupportedException)
        {
            return false; // hygiene must never break the scan that triggered it
        }
    }

    /// <summary>
    /// Pure renderer for the generated file: a short generated-by/edit-freely header, the baseline noise
    /// patterns (<see cref="VendorScan.BaselinePatterns"/>), and the detected vendor directories as
    /// gitignore-style <c>dir/</c> patterns. <paramref name="generatedAtUtc"/> is injected for determinism.
    /// </summary>
    /// <exception cref="ArgumentNullException"><paramref name="vendorDirectories"/> is null.</exception>
    public static string RenderContent(IReadOnlyList<string> vendorDirectories, DateTime generatedAtUtc)
    {
        ArgumentNullException.ThrowIfNull(vendorDirectories);

        var sb = new StringBuilder();
        string date = generatedAtUtc.ToString("yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture);
        sb.Append("# .julieignore — code-intelligence exclusion patterns (gitignore syntax)\n");
        sb.Append("# Generated by Miller on ").Append(date).Append(": no .julieignore existed, so Miller\n");
        sb.Append("# seeded baseline noise patterns plus auto-detected vendor/build directories.\n");
        sb.Append("# Edit freely — Miller never overwrites or appends to this file. Excluded files\n");
        sb.Append("# stay out of symbol extraction and search; delete a line to re-include its files\n");
        sb.Append("# on the next scan. To opt out entirely, keep an empty .julieignore.\n");
        sb.Append('\n');
        sb.Append("# Baseline noise (logs are index noise; use Miller's log tooling to read them)\n");
        foreach (string pattern in VendorScan.BaselinePatterns)
            sb.Append(pattern).Append('\n');

        if (vendorDirectories.Count > 0)
        {
            sb.Append('\n');
            sb.Append("# Auto-detected vendor/build directories\n");
            foreach (string directory in vendorDirectories)
                sb.Append(directory).Append("/\n");
        }
        return sb.ToString();
    }

    // Bounded, non-throwing walk yielding root-relative paths with forward slashes. Unreadable
    // subdirectories are skipped rather than failing the whole detection.
    private static IEnumerable<string> EnumerateRelativeFiles(string workspaceRoot)
    {
        var pending = new Stack<string>();
        pending.Push(workspaceRoot);
        int yielded = 0;

        while (pending.Count > 0 && yielded < MaxEnumeratedFiles)
        {
            string directory = pending.Pop();
            string[] files;
            string[] subdirectories;
            try
            {
                files = Directory.GetFiles(directory);
                subdirectories = Directory.GetDirectories(directory);
            }
            catch (Exception ex) when (
                ex is IOException or UnauthorizedAccessException or System.Security.SecurityException)
            {
                continue;
            }

            foreach (string file in files)
            {
                if (yielded >= MaxEnumeratedFiles)
                    yield break;
                yielded++;
                yield return Path.GetRelativePath(workspaceRoot, file).Replace('\\', '/');
            }

            foreach (string subdirectory in subdirectories)
            {
                string name = Path.GetFileName(subdirectory);
                if (!WalkSkipDirectories.Contains(name))
                    pending.Push(subdirectory);
            }
        }
    }
}
