using System.Text;

namespace Miller.Indexing;

/// <summary>
/// Miller's own <c>--ignore-file</c> contribution to a julie-extract invocation. User-authored and inherited
/// policy remains in-tree; only the generated global policy is eligible for this external list.
///
/// <para><b>The invariant file.</b> <c>&lt;root&gt;/.miller/invariant.julieignore</c> is generated before every
/// scan and passed LAST, which makes its exclusions decisive over every in-tree
/// <c>.gitignore</c>/<c>.julieignore</c> rule (julie-extract concatenates every <c>--ignore-file</c> into ONE
/// <c>GitignoreBuilder</c> in argv order, so ordinary gitignore last-match-wins applies). It holds exclusions
/// ONLY — a whitelist (<c>!</c>) pattern here would be equally decisive and could silently re-include something
/// the user deliberately excluded, so <see cref="InvariantPatterns"/> is guarded against one.</para>
///
/// <para>It closes the nested-worktree double-indexing hole generically. julie-extract hard-excludes
/// <c>.git/ .hg/ .svn/ node_modules/ vendor/ target/ dist/ build/ .cache/ .julie/ .memories/</c> but NOT
/// <c>.miller/</c>, <c>.worktrees/</c>, or <c>.claude/worktrees/</c>, so a repo whose agent worktrees live
/// under its own root had every worktree indexed a second time by the parent workspace.</para>
///
/// <para>NOTE — a behavior change for existing roots: <c>.miller/</c> was previously excluded only by a
/// Miller-SEEDED <c>.julieignore</c> (<see cref="VendorScan.BaselinePatterns"/>). A root with a user-authored
/// <c>.julieignore</c> that lacks the pattern had Miller's own sidecar indexed — <c>.miller/logs/*.jsonl</c>
/// were extracted as JSON source. Those rows disappear on the next scan.</para>
///
/// <para><b>Why only Miller-authored files are ever passed this way.</b> A caller-supplied ignore file is
/// operator configuration to julie-extract: an unreadable file, or a line <c>GitignoreBuilder::add_line</c>
/// rejects (for example <c>a{b</c>), is a HARD failure — exit 1, <c>status=failed</c>, an <c>invalid_path</c>
/// diagnostic, and NO artifact written. The same content IN-TREE only warns. Miller therefore never routes
/// user-authored policy through <c>--ignore-file</c>; a worktree inherits the main checkout's file as an
/// in-tree COPY instead (<see cref="JulieIgnoreSeeder"/>), where the hazard does not exist. This file is
/// generated by Miller, so it is always readable and always parses.</para>
/// </summary>
public static class ScanIgnorePolicy
{
    /// <summary>Miller's per-workspace sidecar directory, which holds the generated invariant file.</summary>
    public const string MillerDirectoryName = ".miller";

    /// <summary>The generated, Miller-owned ignore file's name inside <see cref="MillerDirectoryName"/>.</summary>
    public const string InvariantIgnoreFileName = "invariant.julieignore";

    /// <summary>
    /// The exclusions Miller enforces on every scan regardless of in-tree policy: its own sidecar directory and
    /// the two conventional nested-worktree locations. Exclusions only — never a <c>!</c> whitelist.
    /// </summary>
    public static IReadOnlyList<string> InvariantPatterns { get; } =
        new[] { ".miller/", ".worktrees/", ".claude/worktrees/" };

    /// <summary>
    /// Pure renderer for the generated invariant file. Deterministic (no timestamp) so a scan rewrites identical
    /// bytes, and comment-only apart from <see cref="InvariantPatterns"/>.
    /// </summary>
    public static string RenderInvariantContent()
    {
        var sb = new StringBuilder();
        sb.Append("# Miller invariant exclusions — GENERATED, rewritten on every scan. Edits are lost.\n");
        sb.Append("# Passed to julie-extract as the LAST --ignore-file, so these exclusions win over every\n");
        sb.Append("# in-tree .gitignore/.julieignore rule. Exclusions only: a whitelist here would be just as\n");
        sb.Append("# decisive and could re-include something you excluded on purpose.\n");
        sb.Append("# Put your own patterns in .julieignore at the workspace root instead.\n");
        foreach (string pattern in InvariantPatterns)
            sb.Append(pattern).Append('\n');
        return sb.ToString();
    }

    /// <summary>The absolute path of the generated invariant file for <paramref name="workspaceRoot"/>.</summary>
    /// <exception cref="ArgumentException"><paramref name="workspaceRoot"/> is null or blank.</exception>
    public static string InvariantIgnorePathFor(string workspaceRoot)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(workspaceRoot);
        return Path.Combine(workspaceRoot, MillerDirectoryName, InvariantIgnoreFileName);
    }

    /// <summary>
    /// Rewrite the invariant file and return the ordered <c>--ignore-file</c> list for a scan, or an empty list
    /// when it could not be written — index hygiene must never break the scan that asked for it. The overload
    /// taking an <see cref="EffectiveIgnorePolicy"/> places only a generated global policy before the invariant.
    /// </summary>
    /// <exception cref="ArgumentException"><paramref name="workspaceRoot"/> is null or blank.</exception>
    public static IReadOnlyList<string> PrepareForScan(string workspaceRoot)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(workspaceRoot);
        return WriteInvariantIgnoreFile(workspaceRoot) is { } path
            ? new[] { path }
            : Array.Empty<string>();
    }

    public static IReadOnlyList<string> PrepareForScan(
        string workspaceRoot, EffectiveIgnorePolicy? policy)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(workspaceRoot);
        var paths = new List<string>();
        if (UsesGeneratedPolicy(workspaceRoot, policy))
            paths.Add(policy!.Path);
        if (WriteInvariantIgnoreFile(workspaceRoot) is { } invariant)
            paths.Add(invariant);
        return paths;
    }

    /// <summary>
    /// The <c>--ignore-file</c> list for a single-file <c>update</c>: the generated global policy, when active,
    /// followed by the invariant file if a scan has already written it, else empty. julie-extract's contract is that an <c>update</c> can never insert rows for a
    /// file a fresh <c>scan</c> would not produce, and the invariant exclusions are decisive only when passed —
    /// verified: an <c>update</c> targeting a <c>.worktrees/</c> file writes its symbols WITHOUT this flag and
    /// reports <c>unsupported</c> with it. Never WRITES the file: every workspace reaches its first update
    /// through <see cref="JulieExtractRunner.Scan"/>, and rewriting it under a live event stream would race the
    /// extractor's read of it.
    /// </summary>
    /// <exception cref="ArgumentException"><paramref name="workspaceRoot"/> is null or blank.</exception>
    public static IReadOnlyList<string> ForFileUpdate(string workspaceRoot)
    {
        string path = InvariantIgnorePathFor(workspaceRoot);
        return File.Exists(path) ? new[] { path } : Array.Empty<string>();
    }

    public static IReadOnlyList<string> ForFileUpdate(
        string workspaceRoot, EffectiveIgnorePolicy? policy)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(workspaceRoot);
        var paths = new List<string>();
        if (UsesGeneratedPolicy(workspaceRoot, policy))
            paths.Add(policy!.Path);
        string invariant = InvariantIgnorePathFor(workspaceRoot);
        if (File.Exists(invariant))
            paths.Add(invariant);
        return paths;
    }

    private static bool UsesGeneratedPolicy(string workspaceRoot, EffectiveIgnorePolicy? policy) =>
        policy?.Source == IgnorePolicySource.GeneratedGlobal
        && !File.Exists(Path.Combine(workspaceRoot, JulieIgnoreSeeder.WorkspaceIgnoreFileName))
        && JulieIgnoreSeeder.ResolveInheritedIgnoreFile(workspaceRoot) is null
        && File.Exists(policy.Path);

    /// <summary>
    /// Rewrite <c>&lt;root&gt;/.miller/invariant.julieignore</c> from <see cref="RenderInvariantContent"/> and
    /// return its path, or null when the root does not exist or the file could not be written.
    /// </summary>
    /// <remarks>
    /// Last-writer-wins is DELIBERATE here, and the opposite of the exclusive create
    /// <see cref="JulieIgnoreSeeder.EnsureSeeded(string)"/> uses. That one protects a file a USER may author, so a
    /// racing creator must win; this one is generated, Miller-owned, and contracted to be rewritten on every scan
    /// — there is no user content to lose, and racing Miller processes render byte-identical content from
    /// <see cref="InvariantPatterns"/>. An exclusive create would also strand every existing workspace on the
    /// pattern set that happened to be current when its file was first written, so a release that adds an
    /// invariant exclusion would never reach it.
    /// </remarks>
    /// <exception cref="ArgumentException"><paramref name="workspaceRoot"/> is null or blank.</exception>
    public static string? WriteInvariantIgnoreFile(string workspaceRoot)
    {
        string path = InvariantIgnorePathFor(workspaceRoot);
        try
        {
            // A missing root is a caller error julie-extract reports precisely; materializing it here would turn
            // a mistyped root into a silent scan of an empty directory.
            if (!Directory.Exists(workspaceRoot))
                return null;

            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, RenderInvariantContent());
            return path;
        }
        catch (Exception ex) when (
            ex is IOException or UnauthorizedAccessException or System.Security.SecurityException
               or NotSupportedException)
        {
            return null;
        }
    }
}
