using Miller.Core.Graph;
using Miller.Core.References;
using Miller.Core.Search;
using Miller.Indexing;
using Miller.Indexing.Reads;
using Miller.Server.Resolution;
using Miller.Server.Tools;
using Miller.Server.Tools.Context;

namespace Miller.Tests.Server;

internal static class ContextPipelineTestDriver
{
    public static string Run(
        MillerRepositoryIndex index, SmartTargetResolver resolver,
        string query, int tokenBudget, int maxHops,
        IReadOnlyList<string>? entrySymbols, string? failingTest, string? stackTrace, bool json,
        out int selectedCount, out int candidatesExamined)
    {
        ArgumentNullException.ThrowIfNull(index);
        return Run(index, index.Graph, resolver, query, tokenBudget, maxHops,
            entrySymbols, failingTest, stackTrace, json, out selectedCount, out candidatesExamined);
    }

    public static string Run(
        ISymbolLookupIndex index, ISymbolGraphReachability graph, SmartTargetResolver resolver,
        string query, int tokenBudget, int maxHops,
        IReadOnlyList<string>? entrySymbols, string? failingTest, string? stackTrace, bool json,
        out int selectedCount, out int candidatesExamined)
    {
        ArgumentNullException.ThrowIfNull(index);
        ArgumentNullException.ThrowIfNull(graph);
        ArgumentNullException.ThrowIfNull(resolver);
        return RunActionable(
            index,
            graph,
            resolver,
            query,
            tokenBudget,
            maxHops,
            entrySymbols,
            editedFiles: null,
            failingTest,
            stackTrace,
            semanticSeeds: null,
            sourceSeeds: null,
            readBody: null,
            json,
            out selectedCount,
            out candidatesExamined);
    }

    internal static string RunActionable(
        ISymbolLookupIndex index,
        ISymbolGraphReachability graph,
        SmartTargetResolver resolver,
        string query,
        int tokenBudget,
        int maxHops,
        IReadOnlyList<string>? entrySymbols,
        IReadOnlyList<string>? editedFiles,
        string? failingTest,
        string? stackTrace,
        IReadOnlyList<ContextSemanticSeed>? semanticSeeds,
        Func<IndexedSymbol, ExtractReader.BodyReadResult>? readBody,
        bool json,
        out int selectedCount,
        out int candidatesExamined) =>
        RunActionable(
            index,
            graph,
            resolver,
            query,
            tokenBudget,
            maxHops,
            entrySymbols,
            editedFiles,
            failingTest,
            stackTrace,
            semanticSeeds,
            sourceSeeds: null,
            readBody,
            json,
            out selectedCount,
            out candidatesExamined);

    internal static string RunActionable(
        ISymbolLookupIndex index,
        ISymbolGraphReachability graph,
        SmartTargetResolver resolver,
        string query,
        int tokenBudget,
        int maxHops,
        IReadOnlyList<string>? entrySymbols,
        IReadOnlyList<string>? editedFiles,
        string? failingTest,
        string? stackTrace,
        IReadOnlyList<ContextSemanticSeed>? semanticSeeds,
        IReadOnlyList<ContextSourceSeed>? sourceSeeds,
        Func<IndexedSymbol, ExtractReader.BodyReadResult>? readBody,
        bool json,
        out int selectedCount,
        out int candidatesExamined) =>
        RunActionable(
            index,
            graph,
            resolver,
            query,
            tokenBudget,
            maxHops,
            entrySymbols,
            editedFiles,
            failingTest,
            stackTrace,
            semanticSeeds,
            sourceSeeds,
            readBody,
            readOutgoingMany: null,
            json,
            out selectedCount,
            out candidatesExamined);

    internal static string RunActionable(
        ISymbolLookupIndex index,
        ISymbolGraphReachability graph,
        SmartTargetResolver resolver,
        string query,
        int tokenBudget,
        int maxHops,
        IReadOnlyList<string>? entrySymbols,
        IReadOnlyList<string>? editedFiles,
        string? failingTest,
        string? stackTrace,
        IReadOnlyList<ContextSemanticSeed>? semanticSeeds,
        IReadOnlyList<ContextSourceSeed>? sourceSeeds,
        Func<IndexedSymbol, ExtractReader.BodyReadResult>? readBody,
        Func<IReadOnlyList<string>, IReadOnlyDictionary<string, OutgoingReferenceEvidenceSet>>? readOutgoingMany,
        bool json,
        out int selectedCount,
        out int candidatesExamined) =>
        RunActionableWithCancellation(
            index,
            graph,
            resolver,
            query,
            tokenBudget,
            maxHops,
            entrySymbols,
            editedFiles,
            failingTest,
            stackTrace,
            semanticSeeds,
            sourceSeeds,
            readBody,
            readOutgoingMany,
            json,
            out selectedCount,
            out candidatesExamined,
            CancellationToken.None);

    internal static string RunActionableWithCancellation(
        ISymbolLookupIndex index,
        ISymbolGraphReachability graph,
        SmartTargetResolver resolver,
        string query,
        int tokenBudget,
        int maxHops,
        IReadOnlyList<string>? entrySymbols,
        IReadOnlyList<string>? editedFiles,
        string? failingTest,
        string? stackTrace,
        IReadOnlyList<ContextSemanticSeed>? semanticSeeds,
        IReadOnlyList<ContextSourceSeed>? sourceSeeds,
        Func<IndexedSymbol, ExtractReader.BodyReadResult>? readBody,
        Func<IReadOnlyList<string>, IReadOnlyDictionary<string, OutgoingReferenceEvidenceSet>>? readOutgoingMany,
        bool json,
        out int selectedCount,
        out int candidatesExamined,
        CancellationToken cancellationToken,
        Action<string>? phaseObserver = null,
        ContextQueryRetrieval? retrieval = null)
    {
        ContextResolvedQueryResult result = ContextQueryService.ExecuteResolved(new ContextResolvedQueryRequest(
            index,
            graph,
            resolver,
            query,
            tokenBudget,
            maxHops,
            entrySymbols?.ToArray(),
            editedFiles?.ToArray(),
            failingTest,
            stackTrace,
            ContextReferenceMode.Off,
            ReferenceDepth: 0,
            ExcludeTests: false,
            json,
            semanticSeeds,
            sourceSeeds,
            readBody,
            readOutgoingMany,
            ReadReferenceEvidence: null,
            ReadOutgoingEvidence: null,
            ReadContentChunks: null,
            ReadMany: null,
            cancellationToken,
            (phase, _) => phaseObserver?.Invoke(phase),
            retrieval));
        selectedCount = result.SelectedCount;
        candidatesExamined = result.CandidatesExamined;
        return result.Output;
    }


    internal static string RunReferenceAware(
        ISymbolLookupIndex index, ISymbolGraphReachability graph, SmartTargetResolver resolver,
        string query, int tokenBudget, int maxHops,
        IReadOnlyList<string>? entrySymbols, string? failingTest, string? stackTrace,
        int referenceDepth, bool excludeTests, bool json,
        Func<IndexedSymbol, ReferenceEvidenceSet> readReferenceEvidence,
        Func<IndexedSymbol, OutgoingReferenceEvidenceSet> readOutgoingEvidence,
        Func<IReadOnlyList<IndexedSymbol>, bool, IReadOnlyList<TextContentSearchHit>> readContentChunks,
        out int selectedCount, out int candidatesExamined)
        => RunReferenceAwareActionable(
            index,
            graph,
            resolver,
            query,
            tokenBudget,
            maxHops,
            entrySymbols,
            editedFiles: null,
            failingTest,
            stackTrace,
            semanticSeeds: null,
            sourceSeeds: null,
            readBody: null,
            referenceDepth,
            excludeTests,
            json,
            readReferenceEvidence,
            readOutgoingEvidence,
            readContentChunks,
            out selectedCount,
            out candidatesExamined);

    internal static string RunReferenceAware(
        ISymbolLookupIndex index, ISymbolGraphReachability graph, SmartTargetResolver resolver,
        string query, int tokenBudget, int maxHops,
        IReadOnlyList<string>? entrySymbols, string? failingTest, string? stackTrace,
        int referenceDepth, bool excludeTests, bool json,
        Func<IndexedSymbol, ReferenceEvidenceSet> readReferenceEvidence,
        Func<IndexedSymbol, OutgoingReferenceEvidenceSet> readOutgoingEvidence,
        Func<IReadOnlyList<IndexedSymbol>, bool, IReadOnlyList<TextContentSearchHit>> readContentChunks,
        Func<IReadOnlyList<IndexedSymbol>, IReadOnlyDictionary<string, ReferenceEvidenceBundle>> readMany,
        out int selectedCount, out int candidatesExamined)
        => RunReferenceAwareActionable(
            index,
            graph,
            resolver,
            query,
            tokenBudget,
            maxHops,
            entrySymbols,
            editedFiles: null,
            failingTest,
            stackTrace,
            semanticSeeds: null,
            sourceSeeds: null,
            readBody: null,
            referenceDepth,
            excludeTests,
            json,
            readReferenceEvidence,
            readOutgoingEvidence,
            readContentChunks,
            readMany,
            out selectedCount,
            out candidatesExamined);

    internal static string RunReferenceAwareActionable(
        ISymbolLookupIndex index,
        ISymbolGraphReachability graph,
        SmartTargetResolver resolver,
        string query,
        int tokenBudget,
        int maxHops,
        IReadOnlyList<string>? entrySymbols,
        IReadOnlyList<string>? editedFiles,
        string? failingTest,
        string? stackTrace,
        IReadOnlyList<ContextSemanticSeed>? semanticSeeds,
        Func<IndexedSymbol, ExtractReader.BodyReadResult>? readBody,
        int referenceDepth,
        bool excludeTests,
        bool json,
        Func<IndexedSymbol, ReferenceEvidenceSet> readReferenceEvidence,
        Func<IndexedSymbol, OutgoingReferenceEvidenceSet> readOutgoingEvidence,
        Func<IReadOnlyList<IndexedSymbol>, bool, IReadOnlyList<TextContentSearchHit>> readContentChunks,
        out int selectedCount,
        out int candidatesExamined) =>
        RunReferenceAwareActionable(
            index,
            graph,
            resolver,
            query,
            tokenBudget,
            maxHops,
            entrySymbols,
            editedFiles,
            failingTest,
            stackTrace,
            semanticSeeds,
            sourceSeeds: null,
            readBody,
            referenceDepth,
            excludeTests,
            json,
            readReferenceEvidence,
            readOutgoingEvidence,
            readContentChunks,
            out selectedCount,
            out candidatesExamined);

    internal static string RunReferenceAwareActionable(
        ISymbolLookupIndex index,
        ISymbolGraphReachability graph,
        SmartTargetResolver resolver,
        string query,
        int tokenBudget,
        int maxHops,
        IReadOnlyList<string>? entrySymbols,
        IReadOnlyList<string>? editedFiles,
        string? failingTest,
        string? stackTrace,
        IReadOnlyList<ContextSemanticSeed>? semanticSeeds,
        IReadOnlyList<ContextSourceSeed>? sourceSeeds,
        Func<IndexedSymbol, ExtractReader.BodyReadResult>? readBody,
        int referenceDepth,
        bool excludeTests,
        bool json,
        Func<IndexedSymbol, ReferenceEvidenceSet> readReferenceEvidence,
        Func<IndexedSymbol, OutgoingReferenceEvidenceSet> readOutgoingEvidence,
        Func<IReadOnlyList<IndexedSymbol>, bool, IReadOnlyList<TextContentSearchHit>> readContentChunks,
        out int selectedCount,
        out int candidatesExamined) =>
        RunReferenceAwareActionableWithCancellation(
            index,
            graph,
            resolver,
            query,
            tokenBudget,
            maxHops,
            entrySymbols,
            editedFiles,
            failingTest,
            stackTrace,
            semanticSeeds,
            sourceSeeds,
            readBody,
            referenceDepth,
            excludeTests,
            json,
            readReferenceEvidence,
            readOutgoingEvidence,
            readContentChunks,
            out selectedCount,
            out candidatesExamined,
            CancellationToken.None);

    internal static string RunReferenceAwareActionable(
        ISymbolLookupIndex index,
        ISymbolGraphReachability graph,
        SmartTargetResolver resolver,
        string query,
        int tokenBudget,
        int maxHops,
        IReadOnlyList<string>? entrySymbols,
        IReadOnlyList<string>? editedFiles,
        string? failingTest,
        string? stackTrace,
        IReadOnlyList<ContextSemanticSeed>? semanticSeeds,
        IReadOnlyList<ContextSourceSeed>? sourceSeeds,
        Func<IndexedSymbol, ExtractReader.BodyReadResult>? readBody,
        int referenceDepth,
        bool excludeTests,
        bool json,
        Func<IndexedSymbol, ReferenceEvidenceSet> readReferenceEvidence,
        Func<IndexedSymbol, OutgoingReferenceEvidenceSet> readOutgoingEvidence,
        Func<IReadOnlyList<IndexedSymbol>, bool, IReadOnlyList<TextContentSearchHit>> readContentChunks,
        Func<IReadOnlyList<IndexedSymbol>, IReadOnlyDictionary<string, ReferenceEvidenceBundle>> readMany,
        out int selectedCount,
        out int candidatesExamined) =>
        RunReferenceAwareActionableWithCancellation(
            index,
            graph,
            resolver,
            query,
            tokenBudget,
            maxHops,
            entrySymbols,
            editedFiles,
            failingTest,
            stackTrace,
            semanticSeeds,
            sourceSeeds,
            readBody,
            referenceDepth,
            excludeTests,
            json,
            readReferenceEvidence,
            readOutgoingEvidence,
            readContentChunks,
            readMany,
            out selectedCount,
            out candidatesExamined,
            CancellationToken.None);

    internal static string RunReferenceAwareActionableWithCancellation(
        ISymbolLookupIndex index,
        ISymbolGraphReachability graph,
        SmartTargetResolver resolver,
        string query,
        int tokenBudget,
        int maxHops,
        IReadOnlyList<string>? entrySymbols,
        IReadOnlyList<string>? editedFiles,
        string? failingTest,
        string? stackTrace,
        IReadOnlyList<ContextSemanticSeed>? semanticSeeds,
        IReadOnlyList<ContextSourceSeed>? sourceSeeds,
        Func<IndexedSymbol, ExtractReader.BodyReadResult>? readBody,
        int referenceDepth,
        bool excludeTests,
        bool json,
        Func<IndexedSymbol, ReferenceEvidenceSet> readReferenceEvidence,
        Func<IndexedSymbol, OutgoingReferenceEvidenceSet> readOutgoingEvidence,
        Func<IReadOnlyList<IndexedSymbol>, bool, IReadOnlyList<TextContentSearchHit>> readContentChunks,
        out int selectedCount,
        out int candidatesExamined,
        CancellationToken cancellationToken) =>
        RunReferenceAwareActionableWithCancellation(
            index,
            graph,
            resolver,
            query,
            tokenBudget,
            maxHops,
            entrySymbols,
            editedFiles,
            failingTest,
            stackTrace,
            semanticSeeds,
            sourceSeeds,
            readBody,
            referenceDepth,
            excludeTests,
            json,
            readReferenceEvidence,
            readOutgoingEvidence,
            readContentChunks,
            readMany: null,
            out selectedCount,
            out candidatesExamined,
            cancellationToken);

    internal static string RunReferenceAwareActionableWithCancellation(
        ISymbolLookupIndex index,
        ISymbolGraphReachability graph,
        SmartTargetResolver resolver,
        string query,
        int tokenBudget,
        int maxHops,
        IReadOnlyList<string>? entrySymbols,
        IReadOnlyList<string>? editedFiles,
        string? failingTest,
        string? stackTrace,
        IReadOnlyList<ContextSemanticSeed>? semanticSeeds,
        IReadOnlyList<ContextSourceSeed>? sourceSeeds,
        Func<IndexedSymbol, ExtractReader.BodyReadResult>? readBody,
        int referenceDepth,
        bool excludeTests,
        bool json,
        Func<IndexedSymbol, ReferenceEvidenceSet> readReferenceEvidence,
        Func<IndexedSymbol, OutgoingReferenceEvidenceSet> readOutgoingEvidence,
        Func<IReadOnlyList<IndexedSymbol>, bool, IReadOnlyList<TextContentSearchHit>> readContentChunks,
        Func<IReadOnlyList<IndexedSymbol>, IReadOnlyDictionary<string, ReferenceEvidenceBundle>>? readMany,
        out int selectedCount,
        out int candidatesExamined,
        CancellationToken cancellationToken,
        Action<string>? phaseObserver = null,
        ContextQueryRetrieval? retrieval = null,
        Action<ContextReferenceReadCounts>? referenceReadObserver = null)
    {
        ContextResolvedQueryResult result = ContextQueryService.ExecuteResolved(new ContextResolvedQueryRequest(
            index,
            graph,
            resolver,
            query,
            tokenBudget,
            maxHops,
            entrySymbols?.ToArray(),
            editedFiles?.ToArray(),
            failingTest,
            stackTrace,
            ContextReferenceMode.Usage,
            referenceDepth,
            excludeTests,
            json,
            semanticSeeds,
            sourceSeeds,
            readBody,
            ReadOutgoingMany: null,
            readReferenceEvidence,
            readOutgoingEvidence,
            readContentChunks,
            readMany,
            cancellationToken,
            (phase, counts) =>
            {
                if (counts is { } observedCounts)
                    referenceReadObserver?.Invoke(observedCounts);
                phaseObserver?.Invoke(phase);
            },
            retrieval));
        selectedCount = result.SelectedCount;
        candidatesExamined = result.CandidatesExamined;
        return result.Output;
    }

}
