using Miller.Indexing;
using Xunit;

namespace Miller.Tests.Indexing;

/// <summary>
/// Pins the <c>.julieignore</c> seeding edge (the consumer-side port of julie's
/// <c>generate_julieignore_file()</c>): generated once when absent, NEVER overwritten or appended, with the
/// baseline noise patterns plus detected vendor dirs in gitignore syntax. Tiny temp trees — fast suite (the
/// same pattern as <c>WatchPathFilterTests</c>; no subprocess anywhere on this path).
/// </summary>
public sealed class JulieIgnoreSeederTests
{
    private sealed class TempDir : IDisposable
    {
        public TempDir()
        {
            Path = System.IO.Path.Combine(
                System.IO.Path.GetTempPath(),
                "miller-julieignore-seed-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(Path);
        }

        public string Path { get; }

        public void Dispose() => Directory.Delete(Path, recursive: true);
    }

    private static void WriteTree(string root, params string[] relativeFiles)
    {
        foreach (string relative in relativeFiles)
        {
            string full = System.IO.Path.Combine(root, relative.Replace('/', System.IO.Path.DirectorySeparatorChar));
            Directory.CreateDirectory(System.IO.Path.GetDirectoryName(full)!);
            File.WriteAllText(full, "// fixture");
        }
    }

    [Fact]
    public void EnsureSeeded_NoExistingFile_WritesBaselineAndDetectedVendorDirs()
    {
        using var temp = new TempDir();
        WriteTree(
            temp.Path,
            "src/main.cs",
            "node_modules/a/1.js", "node_modules/a/2.js", "node_modules/b/3.js",
            "node_modules/b/4.js", "node_modules/c/5.js", "node_modules/c/6.js");

        Assert.True(JulieIgnoreSeeder.EnsureSeeded(temp.Path));

        string content = File.ReadAllText(System.IO.Path.Combine(temp.Path, ".julieignore"));
        Assert.StartsWith("# .julieignore", content, StringComparison.Ordinal);
        Assert.Contains("Generated by Miller", content, StringComparison.Ordinal);
        Assert.Contains("Edit freely", content, StringComparison.Ordinal);
        Assert.Contains("\n*.log\n", content, StringComparison.Ordinal);
        Assert.Contains("\n.miller/\n", content, StringComparison.Ordinal);
        Assert.Contains("\nnode_modules/\n", content, StringComparison.Ordinal);
    }

    [Fact]
    public void EnsureSeeded_ExistingFile_IsNeverOverwrittenOrAppended()
    {
        using var temp = new TempDir();
        WriteTree(temp.Path, "node_modules/a/1.js", "node_modules/a/2.js");
        string ignorePath = System.IO.Path.Combine(temp.Path, ".julieignore");
        const string UserAuthored = "# mine — hands off\nonly_this/\n";
        File.WriteAllText(ignorePath, UserAuthored);

        Assert.False(JulieIgnoreSeeder.EnsureSeeded(temp.Path));

        Assert.Equal(UserAuthored, File.ReadAllText(ignorePath)); // byte-for-byte untouched
    }

    [Fact]
    public void EnsureSeeded_SecondCall_IsANoOp_BecauseTheFirstGenerationNowExists()
    {
        using var temp = new TempDir();
        WriteTree(temp.Path, "src/main.cs");

        Assert.True(JulieIgnoreSeeder.EnsureSeeded(temp.Path));
        string first = File.ReadAllText(System.IO.Path.Combine(temp.Path, ".julieignore"));

        Assert.False(JulieIgnoreSeeder.EnsureSeeded(temp.Path));
        Assert.Equal(first, File.ReadAllText(System.IO.Path.Combine(temp.Path, ".julieignore")));
    }

    [Fact]
    public void EnsureSeeded_MissingRoot_ReturnsFalse_NeverThrows()
    {
        string missing = System.IO.Path.Combine(
            System.IO.Path.GetTempPath(), "miller-julieignore-missing-" + Guid.NewGuid().ToString("N"));
        Assert.False(JulieIgnoreSeeder.EnsureSeeded(missing));
    }

    [Fact]
    public void EnsureSeeded_DetectionWalk_SkipsVcsInternals_ButDescendsIntoVendorDirs()
    {
        using var temp = new TempDir();
        // 6 junk files under .git must NOT make ".git" (or anything) a vendor pattern; 6 under dist MUST.
        WriteTree(
            temp.Path,
            ".git/objects/aa/1", ".git/objects/aa/2", ".git/objects/bb/3",
            ".git/objects/bb/4", ".git/objects/cc/5", ".git/objects/cc/6",
            "dist/a/1.js", "dist/a/2.js", "dist/b/3.js", "dist/b/4.js", "dist/c/5.js", "dist/c/6.js",
            "src/main.cs");

        Assert.True(JulieIgnoreSeeder.EnsureSeeded(temp.Path));

        string content = File.ReadAllText(System.IO.Path.Combine(temp.Path, ".julieignore"));
        Assert.Contains("\ndist/\n", content, StringComparison.Ordinal);
        Assert.DoesNotContain(".git", content, StringComparison.Ordinal);
    }

    [Fact]
    public void RenderContent_CleanTree_HasHeaderAndBaseline_NoVendorSection()
    {
        string content = JulieIgnoreSeeder.RenderContent(
            Array.Empty<string>(), new DateTime(2026, 6, 11, 0, 0, 0, DateTimeKind.Utc));

        Assert.StartsWith("# .julieignore", content, StringComparison.Ordinal);
        Assert.Contains("Generated by Miller on 2026-06-11", content, StringComparison.Ordinal);
        Assert.Contains("\n*.log\n", content, StringComparison.Ordinal);
        Assert.Contains("\n.miller/\n", content, StringComparison.Ordinal);
        Assert.DoesNotContain("Auto-detected", content, StringComparison.Ordinal);
        // Every non-comment line must be a usable gitignore pattern (no stray prose).
        foreach (string line in content.Split('\n', StringSplitOptions.RemoveEmptyEntries))
            Assert.True(line.StartsWith('#') || line is "*.log" or ".miller/", $"unexpected non-pattern line: '{line}'");
    }

    [Fact]
    public void RenderContent_VendorDirs_AreEmittedAsDirectoryPatterns()
    {
        string content = JulieIgnoreSeeder.RenderContent(
            new[] { "node_modules", "wwwroot/scripts" },
            new DateTime(2026, 6, 11, 0, 0, 0, DateTimeKind.Utc));

        Assert.Contains("\nnode_modules/\n", content, StringComparison.Ordinal);
        Assert.Contains("\nwwwroot/scripts/\n", content, StringComparison.Ordinal);
    }
}
